#!/bin/bash

CmdName=$(basename "$0")

set -e
set -o pipefail

Syntax="${CmdName} [-d TmpDir][-n] {-f Id2FwFilePathJsonFile} {-i Id2LabelsJsonFile} [-v] {SubjectUid}"

function sys {
        [ -n "${opt_n}${opt_v}" ] && echo "$@" 1>&2
        [ -z "$opt_n" ] && "$@"
}

function mkAlohaStanza {
	 local AlohaFlag="$1"
	 local AlohaArg="$2"
	 local FileId="$3"
	 local FwFilePath="$4"
	 local Timestamp="$5"
	 local SessionId="$6"

	 echo "{ \"$AlohaFlag\": {
	        \"AlohaArg\":	\"$AlohaArg\"
	      , \"FileId\":	\"$FileId\"
	      , \"FwFilePath\":	\"$FwFilePath\"
	      , \"Timestamp\":	\"$Timestamp\"
	      , \"SessionId\":	\"$SessionId\"
	 }}" | jq .
}

function json2Stanza {
	 local FileId="$1"
	 local Dir="$2"
	 local Id2LabelsFile="$3"
	 local Id2FileLabelsFile="$4"
	 local AlohaArg="$5"
	 local AlohaFlag="$6"
	 local Timestamp="$7"
	 local SessionId="$8"
		
	 local FileName=$(echo "\"$FileId\"" | jq -r --slurpfile Id2Labels "$Id2LabelsJsonFile" '$Id2Labels[][.]')
	 local FwFilePath=$(echo "\"$FileId\"" | jq -r --slurpfile Id2FwFilePath "$Id2FwFilePathJsonFile" '$Id2FwFilePath[][.]')

	 mkAlohaStanza "$AlohaArg" "$AlohaFlag" "$FileId" "$FwFilePath" "$Timestamp" "$SessionId"
}

#
# Get the jobs related to the Baseline session
# fwfind -1 -j -rgz session=66e4737ead8f9c0ea1ce2750 > /tmp/jobs.json
#
# Pull the T1w file ids and see if there is more than one
# *** Should verify Trimmed
# jq 'select(.gear_info.name == "ashs-dev" and .state == "complete") | .config.inputs.T1w.object.file_id' /tmp/jobs.json
#
# This one looks for all input files which would work.... but we just want files in the session
# jq '..|select((.object.modality == "MR") and (.object.classification.Intent | any(. == "Structural")) and (.object.classification.Measurement | any(. == "T1")) and (.object.tags | any(. == "Trimmed")) and (.object.tags | any(. == "AlohaInput")))? | .object.file_id' /tmp/jobs.json
#
# Look through all the session acquisition files for T1/T2
#     .acquisitions[].files[]
#   | select(
#             (.type == "nifti")
#	 and (.modality == "MR")
#         and (.classification.Intent | any("Structural"))
#         and (.classification.Measurement | any("T1"))
#         and (.tags | any(. == "Trimmed"))
#	 and (.tags | any(. == "AlohaInput"))
#     )
#     | [ .name, .file_id] | @csv
#    
# Same for T2
# jq 'select(.gear_info.name == "ashs-dev" and .state == "complete") | .config.inputs.T2w.object.file_id' /tmp/jobs.json
#
# *** make sure to bail if there is more than one T1/T2 for any session
#
# Get the segmented Files - There should be 4, Left/Right for ASHS-PMC-T1/T2
# jq -r 'select(.gear_info.name == "ashs-dev" and .state == "complete") | .outputs[] | select((.tags | length) > 0) | [.file_id, (.tags| sort |join(":")) ] | @csv ' /tmp/jobs.json
#
# For the Followup, do the same T1/T2, and now you have enough to run Aloha
#

function getBaselineStanza {
	 local Dir="$1"
	 local SubjectJsonFile="$2"
	 local Id2LabelsJsonFile="$3"
	 local Id2FwFilePathJsonFile="$4"
	 local BaselineSessionId="$5"

	 local BaselineTrimmedT1FileSelectionJq='.acquisitions[].files[] | select((.tags | (any(. == "Trimmed") and any(. == "AlohaInput"))) and (.classification["Measurement"] | any(. == "T1")) )'
	 local FileJson=$( id2Json "$BaselineSessionId" "$SubjectJsonFile" | jq "$BaselineTrimmedT1FileSelectionJq" )
	 if [ -z "$FileJson" ]
	 then
		 echo "${CmdName} : Could not find BaselineTrimmedT1FileSelectionJq '$BaselineTrimmedT1FileSelectionJq'" 1>&2
		 return 1
	 fi
	 local FileId=$(echo "$FileJson" | jq -r '.file_id')
	 local AcquisitionId=$(echo "$FileJson" | jq -r '.parents.acquisition')
	 local AcquisitionTimestamp=$(jq -r '..|select(._id == "'"$AcquisitionId"'")? | .timestamp' "$SubjectJsonFile")
 	 json2Stanza "$FileId" "$Dir" "$Id2LabelsJsonFile" "$Id2FwFilePathJsonFile" "BaselineTrimmedT1" "-b" "$AcquisitionTimestamp" "$BaselineSessionId"

	 local BaselineLeftSegmentedT1FileSelectionJq='.acquisitions[].files[] | select( .tags | ( any(. == "T1") and any(. == "Segmentation") and any(. == "Left") ) )' 
	 FileJson=$( id2Json "$BaselineSessionId" "$SubjectJsonFile" | jq "$BaselineLeftSegmentedT1FileSelectionJq" )
	 if [ -z "$FileJson" ]
	 then
		 echo "${CmdName} : Could not find BaselineLeftSegmentedT1FileSelectionJq '$BaselineLeftSegmentedT1FileSelectionJq'" 1>&2
		 return 1
	 fi
	 FileId=$(echo "$FileJson" | jq -r '.file_id')
	 AcquisitionId=$(echo "$FileJson" | jq -r '.parents.acquisition')
	 AcquisitionTimestamp=$(jq -r '..|select(._id == "'"$AcquisitionId"'")? | .timestamp' "$SubjectJsonFile")

	 json2Stanza "$FileId" "$Dir" "$Id2LabelsJsonFile" "$Id2FwFilePathJsonFile" "BaselineLeftSegmentedT1" "-r" "$AcquisitionTimestamp" "$BaselineSessionId"

	 local BaselineRightSegmentedT1FileSelectionJq='.acquisitions[].files[] | select( .tags | ( any(. == "T1") and any(. == "Segmentation") and any(. == "Right") ) )'
	 FileJson=$( id2Json "$BaselineSessionId" "$SubjectJsonFile" | jq "$BaselineRightSegmentedT1FileSelectionJq" )
	 if [ -z "$FileJson" ]
	 then
		 echo "${CmdName} : Could not find BaselineRightSegmentedT1FileSelectionJq '$BaselineRightSegmentedT1FileSelectionJq'" 1>&2
		 return 1
	 fi
	 FileId=$(echo "$FileJson" | jq -r '.file_id')
	 AcquisitionId=$(echo "$FileJson" | jq -r '.parents.acquisition')
	 AcquisitionTimestamp=$(jq -r '..|select(._id == "'"$AcquisitionId"'")? | .timestamp' "$SubjectJsonFile")

	 json2Stanza "$FileId" "$Dir" "$Id2LabelsJsonFile" "$Id2FwFilePathJsonFile" "BaselineRightSegmentedT1" "-s" "$AcquisitionTimestamp" "$BaselineSessionId"

	 local BaselineLeftSegmentedT2FileSelectionJq='.acquisitions[].files[] | select( .tags | ( any(. == "T2") and any(. == "Segmentation") and any(. == "Left") ) )'
	 FileJson=$( id2Json "$BaselineSessionId" "$SubjectJsonFile" | jq "$BaselineLeftSegmentedT2FileSelectionJq" )
	 if [ -z "$FileJson" ]
	 then
		 echo "${CmdName} : Could not find BaselineLeftSegmentedT2FileSelectionJq '$BaselineLeftSegmentedT2FileSelectionJq'" 1>&2
		 return 1
	 fi
	 FileId=$(echo "$FileJson" | jq -r '.file_id')
	 AcquisitionId=$(echo "$FileJson" | jq -r '.parents.acquisition')
	 AcquisitionTimestamp=$(jq -r '..|select(._id == "'"$AcquisitionId"'")? | .timestamp' "$SubjectJsonFile")

	 json2Stanza "$FileId" "$Dir" "$Id2LabelsJsonFile" "$Id2FwFilePathJsonFile" "BaselineLeftSegmentedT2" "-t" "$AcquisitionTimestamp" "$BaselineSessionId"

	 local BaselineRightSegmentedT2FileSelectionJq='.acquisitions[].files[] | select( .tags | ( any(. == "T2") and any(. == "Segmentation") and any(. == "Right") ) )'
	 FileJson=$( id2Json "$BaselineSessionId" "$SubjectJsonFile" | jq "$BaselineRightSegmentedT2FileSelectionJq" )
	 if [ -z "$FileJson" ]
	 then
		 echo "${CmdName} : Could not find BaselineRightSegmentedT2FileSelectionJq '$BaselineRightSegmentedT2FileSelectionJq'" 1>&2
		 return 1
	 fi
	 FileId=$(echo "$FileJson" | jq -r '.file_id')
	 AcquisitionId=$(echo "$FileJson" | jq -r '.parents.acquisition')
	 AcquisitionTimestamp=$(jq -r '..|select(._id == "'"$AcquisitionId"'")? | .timestamp' "$SubjectJsonFile")

	 json2Stanza "$FileId" "$Dir" "$Id2LabelsJsonFile" "$Id2FwFilePathJsonFile" "BaselineRightSegmentedT2" "-u" "$AcquisitionTimestamp" "$BaselineSessionId"

	 local BaselineT2FileSelectionJq='.acquisitions[].files[] | select( (.tags | any(. == "AlohaInput")) and (.classification["Measurement"] | any(. == "T2")) )'
	 FileJson=$( id2Json "$BaselineSessionId" "$SubjectJsonFile" | jq "$BaselineT2FileSelectionJq" )
	 if [ -z "$FileJson" ]
	 then
		 echo "${CmdName} : Could not find BaselineT2FileSelectionJq '$BaselineT2FileSelectionJq'" 1>&2
		 return 1
	 fi
	 FileId=$(echo "$FileJson" | jq -r '.file_id')
	 AcquisitionId=$(echo "$FileJson" | jq -r '.parents.acquisition')
	 AcquisitionTimestamp=$(jq -r '..|select(._id == "'"$AcquisitionId"'")? | .timestamp' "$SubjectJsonFile")

	 json2Stanza "$FileId" "$Dir" "$Id2LabelsJsonFile" "$Id2FwFilePathJsonFile" "BaselineT2" "-c" "$AcquisitionTimestamp" "$BaselineSessionId"
		
}

function getFollowupStanza {
	 local Dir="$1"
	 local SubjectJsonFile="$2"
	 local Id2LabelJsonFile="$3"
	 local Id2FwFilePathJsonFile="$4"
	 local FollowupSessionId="$5"

	 local FollowupTrimmedT1FileSelectionJq='.acquisitions[].files[] | select((.tags | (any(. == "Trimmed") and any(. == "AlohaInput"))) and (.classification["Measurement"] | any(. == "T1")) )'
	 local FileJson=$( id2Json "$FollowupSessionId" "$SubjectJsonFile" | jq "$FollowupTrimmedT1FileSelectionJq" )
	 if [ -z "$FileJson" ]
	 then
		 echo "${CmdName} : Could not find FollowupTrimmedT1FileSelectionJq '$FollowupTrimmedT1FileSelectionJq'" 1>&2
		 return 1
	 fi
	 local FileId=$(echo "$FileJson" | jq -r '.file_id')
	 local AcquisitionId=$(echo "$FileJson" | jq -r '.parents.acquisition')
	 local AcquisitionTimestamp=$(jq -r '..|select(._id == "'"$AcquisitionId"'")? | .timestamp' "$SubjectJsonFile")
	 json2Stanza "$FileId" "$Dir" "$Id2LabelsJsonFile" "$Id2FwFilePathJsonFile" "FollowupTrimmedT1" "-f" "$AcquisitionTimestamp" "$FollowupSessionId"

	 local FollowupT2FileSelectionJq='.acquisitions[].files[] | select( (.tags | any(. == "AlohaInput")) and (.classification["Measurement"] | any(. == "T2")) )'
	 FileJson=$( id2Json "$FollowupSessionId" "$SubjectJsonFile" | jq "$FollowupT2FileSelectionJq" )
	 if [ -z "$FileJson" ]
	 then
		 echo "${CmdName} : Could not find FollowupT2FileSelectionJq '$FollowupT2FileSelectionJq'" 1>&2
		 return 1
	 fi
	 FileId=$(echo "$FileJson" | jq -r '.file_id')
	 AcquisitionId=$(echo "$FileJson" | jq -r '.parents.acquisition')
	 AcquisitionTimestamp=$(jq -r '..|select(._id == "'"$AcquisitionId"'")? | .timestamp' "$SubjectJsonFile")
	 json2Stanza "$FileId" "$Dir" "$Id2LabelsJsonFile" "$Id2FwFilePathJsonFile" "FollowupT2" "-g" "$AcquisitionTimestamp" "$FollowupSessionId"
}

function id2Json {
	 local Id="$1"
	 local JsonFile="$2"

	 jq "..|select(._id == \"$Id\")?" "$JsonFile"
}

function mkContainerDirName {
	 local Id="$1"
	 local JsonFile="$2"

	 id2Json "$Id" "$JsonFile" | jq -r '.label + "-" + ._id' | sort -u
}

while getopts d:f:i:nv arg
do
	case "$arg" in
	     d|f|i|n|v)
		eval "opt_${arg}='${OPTARG:=1}'"
		;;
	esac
done

shift $(( "$OPTIND" - 1))

if [ -n "$opt_d" ]
then
	TmpDir="$opt_d"
else
	TmpDir=$(mktemp -d "${TMPDIR:=/tmp}/${CmdName}-XXXXXXX")
fi

Id2LabelsJsonFile="$opt_i"
Id2FwFilePathJsonFile="$opt_f"

SubjectJsonFile="$1"
SubjectId=$(jq -r '._id' "$SubjectJsonFile")
SubjectLabel=$(jq -r '.label' "$SubjectJsonFile")

#
# AlohaDir=/tmp/aloha
# SubjectJsonFile="/tmp/aloha/Subject.json"
# fwget -1 -raG 66e4737e1b4b58bc3236d6d1 > "$SubjectJsonFile"
# SubjectLabel=$(jq -r '.label' "$SubjectJsonFile")
# BaselineJsonFile=${AlohaDir}/${SubjectLabel}/Baseline.json"
# jq -r '..|select(.tags | any(. == "Baseline"))?' "$SubjectJsonFile" > "$BaselineJsonFile"
#
# BaselineTrimmedT1Jq='.acquisitions[].files[] | select((.tags | (any(. == "Trimmed") and any(. == "AlohaInput"))) and (.classification["Measurement"] | any(. == "T1")) )'
# BaselineLeftSegmentedT1=


	SubjectAlohaJson=$(
            #
            # Get the baseline Uids.  Make sure there is only one baseline session
            #
            BaselineSessionId=( $(jq -r '..|select(.tags|any(. == "Baseline"))?' "$SubjectJsonFile" | jq -r ._id) )
            if [ "${#BaselineSessionId[@]}" != 1 ]
            then
                echo "${CmdName} : '${#BaselineSessionId[@]}' baseline sessions found.  Not just one. Bailing" 1>&2
                exit 1
            fi
        
            BaselineDir="$TmpDir"/$(mkContainerDirName "$BaselineSessionId" "$SubjectJsonFile")
            [ -e "$BaselineDir" ] || mkdir -p "$BaselineDir" 
        
	    getBaselineStanza "$BaselineDir" "$SubjectJsonFile" "$Id2LabelsJsonFile" "$Id2FwFilePathJsonFile" "$BaselineSessionId" | jq -s '{"Baseline": (. | add)}'
	    ExitCode="${PIPESTATUS[0]}"
	    if [ "$ExitCode" != 0 ]
	    then
		    echo "${CmdName} : getBaselineStanza failed : ExitCode = '$ExitCode'" 1>&2
		    exit "$ExitCode"
	    fi
        
            FollowupSessionIds=( $(jq -r '..|select(.tags|any(. == "Followup"))?' "$SubjectJsonFile" | jq -r ._id) )
            for FollowupSessionId in "${FollowupSessionIds[@]}"
            do
                FollowupDir="$TmpDir"/$(mkContainerDirName "$FollowupSessionId" "$SubjectJsonFile")        
                getFollowupStanza "$FollowupDir" "$SubjectJsonFile" "$Id2LabelsJsonFile" "$Id2FwFilePathJsonFile" "$FollowupSessionId" | jq -s '. | add'
            done | jq -s '{"Followup": .}'
	)
	if [ "$?" -ne 0 ]
	then
		echo "${CmdName} : Failed to generate SubjectAlohaJson" 1>&2
		exit "$ExitCode"
	fi
	echo "$SubjectAlohaJson" | jq -s 'add | . + { "SubjectId": "'"$SubjectId"'", "SubjectLabel": "'"$SubjectLabel"'", "AlohaDir": "'"$TmpDir"'"}'

