#!/bin/bash


#
# Example:
# bash -x aloha_qc_qsub2 -a /data/holder/Aloha/input/aloha -b /data/holder/Aloha/input/Baseline/18_anat_T2w_acq_2DHiResMTL_anat-T2w_acq-2DHiResMTL_20231116134951_18.nii.gz -f /data/holder/Aloha/input/Followup/18_anat_T2w_acq_2DHiResMTL_anat-T2w_acq-2DHiResMTL_20231219140211_18.nii.gz -L /data/holder/Aloha/input/Baseline/18_anat_T2w_acq_2DHiResMTL_anat-T2w_acq-2DHiResMTL_20231116134951_18_ASHS-PMC-T2_lfseg_heur_left.nii.gz -R /data/holder/Aloha/input/Baseline/18_anat_T2w_acq_2DHiResMTL_anat-T2w_acq-2DHiResMTL_20231116134951_18_ASHS-PMC-T2_lfseg_heur_right.nii.gz -s M90195869 


#
# From:
# bscsub:/project/hippogang_2/pauly/longi_for_ashs_xv/test_aloha/runme.sh
#

CmdName=$(basename "$0")
Syntax="${CmdName} [-a AlohaDir][-b BaseLineT2File][-f FollowupT2File][-L BaseLineLeftSegFile][-l FollowupLeftSegFile][-n][-R BaselineRightSegFile][-r FollowupRightSegFile][-s Subject][-v]"

#
# *** Missing Things:
# ROOT - /project/hippogang_2/pauly/longi_for_ashs_xv/test_aloha
# SUBJECT -
#    ${ROOT}/input/${SUBJECT}
#    ${ROOT}/work/${SUBJECT}
# $TP_BL/t{1,2}_img.nii.gz
# $TP_FU/t{1,2}_img.nii.gz


function aloha_qc_qsub()
{
    SUBJECT=${1?}
    TP_BL=${2?}
    TP_FU=${3?}
    ALOHADIR=${4}

    INPUT=${ROOT}/input/${SUBJECT}
    WORK=${ROOT}/work/${SUBJECT}
    if [[ ! $ALOHADIR ]]; then
        ALOHADIR=${WORK}/aloha_${SUBJECT}_${TP_BL}_${TP_FU}
    fi

    QCDIR=$ALOHADIR/qc
    mkdir -p $QCDIR
    mkdir -p tmp/all_qc

    # Generate QC images for ALOHA
    for side in left right; do

        # Create a temp directory for this side
        SDIR=$TMPDIR/qc_${side}
        mkdir -p $SDIR

        # Take the baseline and followup T2 segmentations. They should align well in halfway space
        SEG_BL=${WORK}/${TP_BL}/preproc/${side}_fineseg_t2.nii.gz
        SEG_FU=${WORK}/${TP_FU}/preproc/${side}_fineseg_t2.nii.gz

        # Upsample the T2 images for ALOHA
        c3d ${INPUT}/${TP_BL}/t2_img.nii.gz -resample 100x100x500% -type ushort -o ${SDIR}/t2_bl_iso.nii.gz
        c3d ${INPUT}/${TP_FU}/t2_img.nii.gz -resample 100x100x500% -type ushort -o ${SDIR}/t2_fu_iso.nii.gz

        # Binarize the segmentations, we don't want all the labels
        c3d $SEG_BL -replace 1 100 3 100 4 100 5 100 7 100 8 100 -thresh 100 inf 1 0 -o $SDIR/seg_bl.nii.gz
#        c3d $SEG_FU -replace 1 100 3 100 4 100 5 100 7 100 8 100 -thresh 100 inf 1 0 -o $SDIR/seg_fu.nii.gz

        # Crop the moving image and match its origin to the cropped fixed image, this
        # should be done for both the image and segmentation
        REF_FU=$ALOHADIR/global/futrimdef_${side}.nii.gz
        REF_FU_OM=$ALOHADIR/deformable/futrimdef_om_${side}.nii.gz
        c3d $REF_FU_OM $REF_FU ${SDIR}/t2_fu_iso.nii.gz -reslice-identity -copy-transform \
            -o $SDIR/t2_fu_om.nii.gz

#       c3d $REF_FU_OM $REF_FU $SDIR/seg_fu.nii.gz -reslice-identity -copy-transform -thresh 0.5 inf 1 0 \
            -o $SDIR/seg_futrimom.nii.gz
    
        # Transform the fixed image to the halfway space
        greedy -d 3 -threads 1 \
            -rf $ALOHADIR/deformable/hwtrimdef_${side}.nii.gz \
            -rm ${SDIR}/t2_bl_iso.nii.gz $SDIR/bltrimhw.nii.gz \
            -ri LABEL 0.2mm -rm $SDIR/seg_bl.nii.gz $SDIR/seg_bltrimhw.nii.gz \
            -r $ALOHADIR/deformable/tse_global_long_${side}_omRAS_half_inv.mat

        # Transform the moving image to the halfway space (affine only)
        greedy -d 3 -threads 1 \
            -rf $ALOHADIR/deformable/hwtrimdef_${side}.nii.gz \
            -rm $SDIR/t2_fu_om.nii.gz $SDIR/futrimom_affine_to_hw.nii.gz \
            -r $ALOHADIR/deformable/tse_global_long_${side}_omRAS_half.mat
#           -ri LABEL 0.2mm -rm $SDIR/seg_futrimom.nii.gz $SDIR/seg_futrimom_affine_to_hw.nii.gz \

        # Generate a warp by combining xyz components from ANTS
        c3d $ALOHADIR/deformable/tse_antsreg3d_${side}Warpxvec.nii.gz \
            $ALOHADIR/deformable/tse_antsreg3d_${side}Warpyvec.nii.gz \
            $ALOHADIR/deformable/tse_antsreg3d_${side}Warpzvec.nii.gz \
            -omc $SDIR/tse_antsreg3d_${side}_warp.nii.gz

        # Transform the moving image to the halfway space (warp and affine)
        greedy -d 3 -threads 1 \
            -rf $ALOHADIR/deformable/hwtrimdef_${side}.nii.gz \
            -rm $SDIR/t2_fu_om.nii.gz $SDIR/futrimom_warped_to_hw.nii.gz \
            -r $SDIR/tse_antsreg3d_${side}_warp.nii.gz $ALOHADIR/deformable/tse_global_long_${side}_omRAS_half.mat
#           -ri LABEL 0.2mm -rm $SDIR/seg_futrimom.nii.gz $SDIR/seg_futrimom_warped_to_hw.nii.gz \

        # Compute overlap between the segmentations in halfway space
#        c3d $SDIR/seg_bltrimhw.nii.gz $SDIR/seg_futrimom_affine_to_hw.nii.gz -overlap 1 > $QCDIR/overlap_affine_${side}.txt            
#        c3d $SDIR/seg_bltrimhw.nii.gz $SDIR/seg_futrimom_warped_to_hw.nii.gz -overlap 1 > $QCDIR/overlap_warped_${side}.txt            

        # Compute NCC metric?
        c3d $SDIR/seg_bltrimhw.nii.gz -dilate 1 5x5x5 -popas M \
            $SDIR/bltrimhw.nii.gz -as R \
            $SDIR/futrimom_affine_to_hw.nii.gz -ncc 2x2x2 -replace nan 0 -push M -lstat \
            > $QCDIR/ncc_affine_${side}.txt

        c3d $SDIR/seg_bltrimhw.nii.gz -dilate 1 5x5x5 -popas M \
            $SDIR/bltrimhw.nii.gz -as R \
            $SDIR/futrimom_warped_to_hw.nii.gz -ncc 2x2x2 -replace nan 0 -push M -lstat \
            > $QCDIR/ncc_warped_${side}.txt

        # Generate a QC image
        c3d $SDIR/bltrimhw.nii.gz -stretch 0% 99% 0 255 -clip 0 255 -popas R \
            $SDIR/futrimom_affine_to_hw.nii.gz -stretch 0% 99% 0 255 -clip 0 255 -popas FA \
            $SDIR/futrimom_warped_to_hw.nii.gz -stretch 0% 99% 0 255 -clip 0 255 -popas FW \
            -push FA -push R -scale -1 -add -stretch -127 128 0 255 -clip 0 255 -popas FA_diff \
            -push FW -push R -scale -1 -add -stretch -127 128 0 255 -clip 0 255 -popas FW_diff \
            -push R -slice z 20%:10%:80% -tile x -flip y -popas row_R \
            -push FA -slice z 20%:10%:80% -tile x -flip y -popas row_FA \
            -push FW -slice z 20%:10%:80% -tile x -flip y -popas row_FW \
            -push FA_diff -slice z 20%:10%:80% -tile x -flip y -popas row_FA_diff \
            -push FW_diff -slice z 20%:10%:80% -tile x -flip y -popas row_FW_diff \
            -push row_R -push row_FA -push row_FA_diff -push row_FW -push row_FW_diff \
            -type uchar -oo $SDIR/qc_${side}_row_%d.png # \
            # -tile y -o $QCDIR/${SUBJECT}_${TP_BL}_${TP_FU}_aloha_qc_${side}.png \

        magick -delay 100 -font DejaVu-Sans -pointsize 12 -background black -fill white \
            \( \
                \( -size 320x20 -gravity center caption:"${SUBJECT} ${TP_BL} - baseline" \) \
                \( \( $SDIR/qc_${side}_row_0.png $SDIR/qc_${side}_row_2.png -append \) \
                \( -size 120x20 -gravity center caption:"affine" -rotate 270 \) \
                +swap +append \) \
                \( \( $SDIR/qc_${side}_row_0.png $SDIR/qc_${side}_row_4.png -append \) \
                \( -size 120x20 -gravity center caption:"deformable" -rotate 270 \) \
                +swap +append \) \
                -append \) \
            \( \
                \( -size 320x20 -gravity center caption:"${SUBJECT} ${TP_FU} - followup" \) \
                \( \( $SDIR/qc_${side}_row_1.png $SDIR/qc_${side}_row_2.png -append \) \
                \( -size 120x20 -gravity center caption:"affine" -rotate 270 \) \
                +swap +append \) \
                \( \( $SDIR/qc_${side}_row_3.png $SDIR/qc_${side}_row_4.png -append \) \
                \( -size 120x20 -gravity center caption:"deformable" -rotate 270 \) \
                +swap +append \) \
                -append \) \
            -loop 0 $QCDIR/${SUBJECT}_${TP_BL}_${TP_FU}_aloha_qc_${side}.gif

        # Also copy the 3D patch images into the QC dir for additional inspection
        c3d $SDIR/bltrimhw.nii.gz -type short $QCDIR/${SUBJECT}_${TP_BL}_${TP_FU}_aloha_qc_${side}_bltrimhw.nii.gz 
        c3d $SDIR/futrimom_affine_to_hw.nii.gz -type short $QCDIR/${SUBJECT}_${TP_BL}_${TP_FU}_aloha_qc_${side}_futrimom_affine_to_hw.nii.gz
        c3d $SDIR/futrimom_warped_to_hw.nii.gz -type short $QCDIR/${SUBJECT}_${TP_BL}_${TP_FU}_aloha_qc_${side}_futrimom_warped_to_hw.nii.gz

        # Copy the gif to a common directory for easy viewing
        cp $QCDIR/${SUBJECT}_${TP_BL}_${TP_FU}_aloha_qc_${side}.gif tmp/all_qc/

    done

    # Generate a single summary qc file
#    OVL_AL=$(cat $QCDIR/overlap_affine_left.txt | sed -e "s/,//g" | awk '{print $6}')
#    OVL_WL=$(cat $QCDIR/overlap_warped_left.txt | sed -e "s/,//g" | awk '{print $6}')
#    OVL_AR=$(cat $QCDIR/overlap_affine_right.txt | sed -e "s/,//g" | awk '{print $6}')
#    OVL_WR=$(cat $QCDIR/overlap_warped_right.txt | sed -e "s/,//g" | awk '{print $6}')
    NCC_AL=$(cat $QCDIR/ncc_affine_left.txt | awk '$1==1 {print $2}')
    NCC_WL=$(cat $QCDIR/ncc_warped_left.txt | awk '$1==1 {print $2}')
    NCC_AR=$(cat $QCDIR/ncc_affine_right.txt | awk '$1==1 {print $2}')
    NCC_WR=$(cat $QCDIR/ncc_warped_right.txt | awk '$1==1 {print $2}') 
    echo "${SUBJECT},${TP_BL},${TP_FU},${OVL_AL},${OVL_WL},${OVL_AR},${OVL_WR},${NCC_AL},${NCC_WL},${NCC_AR},${NCC_WR}" \
        > $QCDIR/${SUBJECT}_${TP_BL}_${TP_FU}_aloha_qc_summary.csv

}

while getopts 'a:b:f:L:l:R:r:n:s:v' arg
do
    case "$arg" in
	a|b|f|L|l|n|R|r|s|v)
	    eval "opt_${arg}='${OPTARG:=1}'"
	    ;;
	*)
	    echo "${CmdName}: Invalid flag '$arg'" 1>&2
	    echo "$Syntax" 1>&2
	    exit 1
    esac
done

shift $(( "$OPTIND" - 1 ))

SUBJECT="$opt_s"

AlohaQcDir="/tmp/AlohaQcDir"
AlohaDir="${AlohaQcDir}/Aloha"
ROOT="$AlohaQcDir"
WORK="${ROOT}/work/${SUBJECT}"
INPUT="${ROOT}/input/${SUBJECT}"
TMPDIR="${AlohaQcDir}/tmp"

# TP_BL is YYYY-MM-DD of baseline directory
# TP_FU is YYYY-MM-DD of followup directory
# copy
#   $opt_b to ${AlohaQcDir}/input/${SUBJECT}/${TP_BL}/t2_img.nii.gz
#   $opt_f to ${INPUT}/${TP_FU}/t2_img.nii.gz
#   $opt_l to $WORK/$TP_BL/preproc/left_fineseg_t2.nii.gz
#   $opt_r to $WORK/$TP_BL/preproc/right_fineseg_t2.nii.gz

if [ -e "$AlohaQcDir" ]
then
	rm -rf "$AlohaQcDir"
else
	mkdir -p "$AlohaQcDir"
fi

cd "$AlohaQcDir"

TP_BL=2023-11-16
TP_FU=2023-12-19

TP_BL_T2File="${AlohaQcDir}/input/${SUBJECT}/${TP_BL}/t2_img.nii.gz"
TP_FU_T2File="${AlohaQcDir}/input/${SUBJECT}/${TP_FU}/t2_img.nii.gz"
TP_BL_Dir=$(dirname "$TP_BL_T2File")
TP_FU_Dir=$(dirname "$TP_FU_T2File")

[ -e "$TP_BL_Dir" ] || mkdir -p "$TP_BL_Dir"
[ -e "$TP_FU_Dir" ] || mkdir -p "$TP_FU_Dir"

[ -e "$TP_BLT2File" ] || cp "$opt_b" "$TP_BL_T2File"
[ -e "$TP_FUT2File" ] || cp "$opt_f" "$TP_FU_T2File"

LeftBlSegFile="${WORK}/${TP_BL}/preproc/left_fineseg_t2.nii.gz"
RightBlSegFile="${WORK}/${TP_BL}/preproc/right_fineseg_t2.nii.gz"
LeftBlSegDir=$(dirname "$LeftBlSegFile")
RightBlSegDir=$(dirname "$RightBlSegFile")

[ -e "$LeftBlSegDir" ] || mkdir -p "$LeftBlSegDir"
[ -e "$RightBlSegDir" ] || mkdir -p "$RightBlSegDir"

[ -e "$LeftBlSegFile" ] || cp "$opt_L" "$LeftBlSegFile"
[ -e "$RightBlSegFile" ] || cp "$opt_R" "$RightBlSegFile"

#
# Alohabackend doesn not produce followup T2 segmented left/right images
#
#LeftFuSegFile="${WORK}/${TP_FU}/preproc/left_fineseg_t2.nii.gz"
#RightFuSegFile="${WORK}/${TP_FU}/preproc/right_fineseg_t2.nii.gz"
#LeftFuSegDir=$(dirname "$LeftFuSegFile")
#RightFuSegDir=$(dirname "$RightFuSegFile")

#[ -e "$LeftFuSegDir" ] || mkdir -p "$LeftFuSegDir"
#[ -e "$RightFuSegDir" ] || mkdir -p "$RightFuSegDir"

#[ -e "$LeftFuSegFile" ] || cp "$opt_l" "$LeftFuSegFile"
#[ -e "$RightFuSegFile" ] || cp "$opt_r" "$RightFuSegFile"


rsync -a "${opt_a}/" "${AlohaDir}/"

aloha_qc_qsub "$SUBJECT" "$TP_BL" "$TP_FU" "$AlohaDir"

