#!/bin/bash

ConfigJsonFile=config.test.json
DownloadDir=input
Jq='
      .inputs
     | to_entries[]
        | .key as $FilePath
        | .value.object.file_id as $FileId
	| [ $FilePath, $FileId ]
        | @csv
'

for line in $(jq -r "$Jq" "$ConfigJsonFile" | grep -v ",$" | sed 's/"//g')
do
	FilePath=$(echo "$line" | cut -f 1 -d ,)
	FileId=$(echo "$line" | cut -f 2 -d ,)

	FullDirectoryPath="${DownloadDir}/${FilePath}"
	[ -e "$FullDirectoryPath" ] || mkdir -p "$FullDirectoryPath"

	fwget -f --download --download-dir "$FullDirectoryPath" "$FileId"
done
